<?php
/**
 * Copyright (c) 2006-2013 Las Venturas Starground
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 */

namespace Spock;

/**
 * Used for ItemId to ItemName and vice versa transitions
 *
 * @author Joeri de Graaf <joeri@oostcoast.nl>
 */
class ItemUtilities {
  private static $m_ItemList = array(
    1 => 'Ship Core', 
    2 => 'SD HCT xm3.4 Power Block',
    3 => 'SD Shield Disperser',
    4 => 'Salvage Computer',
    5 => 'Grey Hull (Normal)',
    6 => 'Weapons Computer',
    7 => 'Turret Dock',
    8 => 'Hyperflux Coil Thruster',
    14 => 'Dis-Integrater (Explosive)',
    15 => '10x Radar Jammer',
    16 => 'Antimatter Cannon',
    22 => '0C Cloaker',
    24 => 'Salvage Cannon',
    30 => 'Astro Technobeam',
    32 => 'd1000 "Dumb" Missile Array',
    38 => 'd1000 "Dumb" Missile CPU',
    39 => 'Astro Technician',
    40 => 'SD KB Heat-seeking Missile Array',
    46 => 'SD KB Heat-seeking Missile CPU',
    47 => 'SD Cockpit',
    48 => 'SD BB Bunker-buster Missile Array',
    54 => 'SD BB Bunker-buster Missile CPU',
    55 => 'Plex Light',
    56 => 'Gravity Unit',
    62 => 'Plex Beacon',
    63 => 'Plex Glass',
    64 => 'Ice',
    69 => 'Purple Hull (Normal)',
    70 => 'Brown Hull (Normal)',
    72 => 'L1 (Extranium)',
    73 => 'Rock',
    74 => 'Sand',
    75 => 'Black Hull (Normal)',
    76 => 'Red Hull (Normal)',
    77 => 'Blue Hull (Normal)',
    78 => 'Green Hull (Normal)',
    79 => 'Yellow Hull (Normal)',
    80 => 'Lava',
    81 => 'White Hull (Normal)',
    82 => 'Grass Planet Dirt',
    83 => 'Grass Planet Terrain',
    84 => 'Wood',
    85 => 'Foliage',
    86 => 'Water',
    87 => 'Soil',
    88 => 'Turret Dock Enhancer',
    89 => 'Cactus',
    90 => 'Purple Stuff',
    91 => 'Purple Rock',
    92 => 'Purple Vine',
    93 => 'Grass Patch',
    94 => 'Plex Un-deathinator',
    95 => 'Brown Patch',
    96 => 'Mars Tentacles',
    97 => 'Alien Vines',
    98 => 'Grass Flowers',
    99 => 'Long Weed',
    100 => 'Tall Mushroom',
    101 => 'Purspire',
    102 => 'Tall Grass Flowers',
    103 => 'Mini Cactus',
    104 => 'Red Mushroom',
    105 => 'Purptacles',
    106 => 'Tall Flowers',
    107 => 'Rock',
    108 => 'Alien Flowers',
    109 => 'Yhole',
    112 => 'Plex Lander',
    113 => 'Plex Lifter',
    114 => 'Plex Recycler',
    120 => 'Plex Storage',
    121 => 'BOBBY AI Module',
    122 => 'Plex Door',
    123 => 'Build Block',
    128 => 'L1 (Exogen)',
    129 => 'L1 (Octogen)',
    130 => 'L1 (Quantagen)',
    131 => 'L1 (Quantanium)',
    132 => 'L1 (Plextanium)',
    133 => 'L1 (Oraguntanium)',
    134 => 'L1 (Succumite)',
    135 => 'L1 (Cenomite)',
    136 => 'L1 (Awesomite)',
    137 => 'L1 (Vappecide)',
    138 => 'Red Planet Terrain',
    139 => 'Red Rock',
    140 => 'Red Dirt',
    141 => 'Red Planet Rock',
    142 => 'L2 (Exogen)',
    143 => 'L3 (Exogen)',
    144 => 'L4 (Exogen)',
    145 => 'L5 (Exogen)',
    146 => 'L2 (Octogen)',
    147 => 'L3 (Octogen)',
    148 => 'L4 (Octogen)',
    149 => 'L5 (Octogen)',
    150 => 'L2 (Quantagen)',
    151 => 'L3 (Quantagen)',
    152 => 'L4 (Quantagen)',
    153 => 'L5 (Quantagen)',
    154 => 'L2 (Quantanium)',
    155 => 'L3 (Quantanium)',
    156 => 'L4 (Quantanium)',
    157 => 'L5 (Quantanium)',
    158 => 'L2 (Plextanium)',
    159 => 'L3 (Plextanium)',
    160 => 'L4 (Plextanium)',
    161 => 'L5 (Plextanium)',
    162 => 'L2 (Oraguntanium)',
    163 => 'L3 (Oraguntanium)',
    164 => 'L4 (Oraguntanium)',
    165 => 'L5 (Oraguntanium)',
    166 => 'L2 (Succumite)',
    167 => 'L3 (Succumite)',
    168 => 'L4 (Succumite)',
    169 => 'L5 (Succumite)',
    170 => 'L2 (Cenomite)',
    171 => 'L3 (Cenomite)',
    172 => 'L4 (Cenomite)',
    173 => 'L5 (Cenomite)',
    174 => 'L2 (Awesomite)',
    175 => 'L3 (Awesomite)',
    176 => 'L4 (Awesomite)',
    177 => 'L5 (Awesomite)',
    178 => 'L2 (Vappecide)',
    179 => 'L3 (Vappecide)',
    180 => 'L4 (Vappecide)',
    181 => 'L5 (Vappecide)',
    182 => 'L2 (Negacide)',
    182 => 'L3 (Negacide)',
    184 => 'L4 (Negacide)',
    185 => 'L5 (Negacide)',
    186 => 'L2 (Quantacide)',
    187 => 'L3 (Quantacide)',
    188 => 'L4 (Quantacide)',
    189 => 'L5 (Quantacide)',
    190 => 'L2 (Negagate)',
    191 => 'L3 (Negagate)',
    192 => 'L4 (Negagate)',
    193 => 'L5 (Negagate)',
    194 => 'L2 (Metate)',
    195 => 'L3 (Metate)',
    196 => 'L4 (Metate)',
    197 => 'L5 (Metate)',
    198 => 'L2 (Insanium)',
    199 => 'L3 (Insanium)',
    200 => 'L4 (Insanium)',
    201 => 'L5 (Insanium)',
    202 => 'L2 (Extranium)',
    203 => 'L3 (Extranium)',
    204 => 'L4 (Extranium)',
    205 => 'L5 (Extranium)',
    206 => 'L1 (Negacide)',
    207 => 'L1 (Quantacide)',
    208 => 'L1 (Negagate)',
    209 => 'L1 (Metate)',
    210 => 'L1 (Insanium)',
    211 => 'Factory Input',
    212 => 'Factory Input Enhancer',
    219 => 'Power Cell',
    220 => 'Power Coil',
    223 => 'Capacitor (SD1000)',
    224 => 'Capacitor (SD2000)',
    225 => 'Capacitor (SD3000)',
    226 => 'Flux Coil (SD1000)',
    227 => 'Flux Coil (SD2000)',
    228 => 'Flux Coil (SD3000)',
    229 => 'Microprocessor (SD1000)',
    230 => 'Microprocessor (SD2000)',
    231 => 'Microprocessor (SD3000)',
    232 => 'Delta Interface (SD1000)',
    233 => 'Delta Interface (SD2000)',
    235 => 'Delta Interface (SD3000)',
    235 => 'Memory Module (SD1000)',
    236 => 'Memory Module (SD2000)',
    237 => 'Memory Module (SD3000)',
    238 => 'SD Proton Reactor',
    239 => 'Red Paint',
    240 => 'Purple Paint',
    241 => 'Brown Paint',
    242 => 'Green Paint',
    243 => 'Yellow Paint',
    244 => 'Black Paint',
    245 => 'White Paint',
    246 => 'Blue Paint',
    247 => '1000b Protein',
    248 => '2000b Protein',
    249 => '3000b Protein',
    250 => '10000a Protein',
    251 => '20000a Protein',
    252 => '30000a Protein',
    253 => '40000a Protein',
    254 => 'Yhole Nucleus',
    255 => 'Schemadyne-10000',
    256 => 'Schemadyne-20000',
    257 => 'Schemadyne-30000',
    258 => 'Schemadyne Advanced',
    259 => 'Schemadyne-1000',
    260 => 'Schemadyne-2000',
    261 => 'Schemadyne-3000',
    262 => 'Mineral Separator',
    263 => 'Grey Hull (hardened)',
    264 => 'Black Hull (hardened)',
    265 => 'Red Hull (hardened)',
    266 => 'Purple Hull (hardened)',
    267 => 'Blue Hull (hardened)',
    268 => 'Green Hull (hardened)',
    269 => 'Brown Hull (hardened)',
    270 => 'Yellow Hull (hardened)',
    271 => 'White Hull (hardened)',
    272 => 'Glass Bottle',
    273 => 'Science Bottle',
    274 => 'Ice Planet Surface',
    275 => 'Ice Planet Rock',
    276 => 'Ice Wood',
    277 => 'Ice Leaves',
    282 => 'Red Light',
    283 => 'Blue Light',
    284 => 'Green Light',
    285 => 'Yellow Light',
    286 => 'Ice Crystal',
    287 => 'Redwood',
    288 => 'Redwood Leaves',
    289 => 'Docking Module',
    290 => 'Docking Enhancer',
    291 => 'Faction Module',
    292 => 'Faction Hub',
    293 => 'Grey Hull Wedge (Normal)',
    294 => 'Purple Hull Wedge (Normal)',
    295 => 'Brown Hull Wedge (Normal)',
    296 => 'Black Hull Wedge (Normal)',
    297 => 'Red Hull Wedge (Normal)',
    298 => 'Blue Hull Wedge (Normal)',
    299 => 'Green Hull Wedge (Normal)',
    300 => 'Yellow Hull Wedge (Normal)',
    301 => 'White Hull Wedge (Normal)',
    302 => 'Grey Hull Corner (Normal)',
    303 => 'Purple Hull Corner (Normal)',
    304 => 'Brown Hull Corner (Normal)',
    305 => 'Black Hull Corner (Normal)',
    306 => 'Red Hull Corner (Normal)',
    307 => 'Blue Hull Corner (Normal)',
    308 => 'Green Hull Corner (Normal)',
    309 => 'Yellow Hull Corner (Normal)',
    310 => 'White Hull Corner (Normal)',
    311 => 'Grey Hull Wedge (hardened)',
    312 => 'Black Hull Wedge (hardened)',
    313 => 'Red Hull Wedge (hardened)',
    314 => 'Purple Hull Wedge (hardened)',
    315 => 'Blue Hull Wedge (hardened)',
    316 => 'Green Hull Wedge (hardened)',
    317 => 'Brown Hull Wedge (hardened)',
    318 => 'Yellow Hull Wedge (hardened)',
    319 => 'White Hull Wedge (hardened)',
    320 => 'Grey Hull Corner (hardened)',
    321 => 'Black Hull Corner (hardened)',
    322 => 'Red Hull Corner (hardened)',
    323 => 'Purple Hull Corner (hardened)',
    324 => 'Blue Hull Corner (hardened)',
    325 => 'Green Hull Corner (hardened)',
    326 => 'Brown Hull Corner (hardened)',
    327 => 'Yellow Hull Corner (hardened)',
    328 => 'White Hull Corner (hardened)',
    329 => 'Plex Glass Wedge',
    330 => 'Plex Glass Corner',
    331 => 'SD pc1.3 Power Tank',
    332 => 'Powerdrain Beam Computer',
    333 => 'Powerdrain Beam',
    334 => 'Powersupply Beam Computer',
    335 => 'Powersupply Beam',
    344 => 'Pulse Computer',
    345 => 'Pulsator');

  public static function getItemName($itemId) {
    if (isset(self::$m_ItemList[$itemId]))
      return self::$m_ItemList[$itemId];
    else
      return false;
  }

  public static function getItemId($itemName) {
    $id = array_search($itemName, self::$m_ItemList);
    if ($id !== false)
      return self::$m_ItemList[$id];
    else
      return false;
  }
};
?>
